// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcalp65FTA0Zv5HFp4-D-BUtdY2DDEXlY',
    appId: '1:405755343892:web:3257ecee2b6a41fdaee301',
    messagingSenderId: '405755343892',
    projectId: 'printex-project-667c9',
    authDomain: 'printex-project-667c9.firebaseapp.com',
    storageBucket: 'printex-project-667c9.firebasestorage.app',
    measurementId: 'G-XYTD7RC8TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOcpJXRq-f7BjcEiE5fTck-Ukg3-N2zc',
    appId: '1:405755343892:android:fd504fc7c30375fbaee301',
    messagingSenderId: '405755343892',
    projectId: 'printex-project-667c9',
    storageBucket: 'printex-project-667c9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcalp65FTA0Zv5HFp4-D-BUtdY2DDEXlY',
    appId: '1:405755343892:web:f11b0c7ba006a330aee301',
    messagingSenderId: '405755343892',
    projectId: 'printex-project-667c9',
    authDomain: 'printex-project-667c9.firebaseapp.com',
    storageBucket: 'printex-project-667c9.firebasestorage.app',
    measurementId: 'G-3G5F4QYQLX',
  );
}
